---

groups:
- name: install
  jobs:
  - install-nsx-t

- name: cleanup
  jobs:
  - uninstall-nsx-t

resources:
- name: nsx-t-gen-pipeline
  type: git
  source:
    uri: https://github.com/sparameswaran/nsx-t-gen.git
    branch: master


jobs:

- name: install-nsx-t
  plan:
  - aggregate:
    - get: nsx-t-gen-pipeline
  - task: install-nsx-t
    file: nsx-t-gen-pipeline/tasks/install-nsx-t/task.yml


- name: uninstall-nsx-t
  plan:
  - aggregate:
    - get: nsx-t-gen-pipeline

  - task: uninstall-nsx-t
    file: nsx-t-gen-pipeline/tasks/uninstall-nsx-t/task.yml

