---
# Use reference instead of repeating the nsx-t params
nsx_t_gen_params: &nsx-t-gen-params
  VCENTER_HOST: {{vcenter_host}}
  VCENTER_USR: {{vcenter_usr}}
  VCENTER_PWD: {{vcenter_pwd}}
  VCENTER_DATACENTER: {{vcenter_datacenter}}
  VCENTER_DATASTORE: {{vcenter_datastore}}
  VCENTER_CLUSTER: {{vcenter_cluster}}
  NTPSERVERS: {{ntpservers}}
  PORTGROUP: {{portgroup}}
  DNSSERVER: {{dnsserver}}
  DNSDOMAIN: {{dnsdomain}}
  DEFAULTGATEWAY: {{defaultgateway}}
  NETMASK: {{netmask}}
  JUMPBOX_IP: {{jumpbox_ip}}
  JUMPBOX_USER: {{jumpbox_user}}
  JUMPBOX_PWD: {{jumpbox_pwd}}
  ESXI_HOST_PWD: {{esxi_host_pwd}}
  ESXI_HOST_IP_PWDS: {{esxi_host_ip_pwds}}
  NSX_T_MANAGER_FQDN: {{nsx_t_manager_fqdn}}
  NSX_T_MANAGER_VM_NAME: {{nsx_t_manager_vm_name}}
  NSX_T_MANAGER_IP: {{nsx_t_manager_ip}}
  NSX_T_MANAGER_ADMIN_PWD: {{nsx_t_manager_admin_pwd}}
  NSX_T_MANAGER_ROOT_PWD: {{nsx_t_manager_root_pwd}}
  NSX_T_CONTROLLER_HOST_PREFIX: {{nsx_t_controller_host_prefix}}
  NSX_T_CONTROLLER_VM_NAME_PREFIX: {{nsx_t_controller_vm_name_prefix}}
  NSX_T_CONTROLLER_IPS: {{nsx_t_controller_ips}}
  NSX_T_CONTROLLER_ROOT_PWD: {{nsx_t_controller_root_pwd}}
  NSX_T_CONTROLLER_CLUSTER_PWD: {{nsx_t_controller_cluster_pwd}}
  NSX_T_EDGE_HOST_PREFIX: {{nsx_t_edge_host_prefix}}
  NSX_T_EDGE_VM_NAME_PREFIX: {{nsx_t_edge_vm_name_prefix}}
  NSX_T_EDGE_IPS: {{nsx_t_edge_ips}}
  NSX_T_EDGE_ROOT_PWD: {{nsx_t_edge_root_pwd}}
  NSX_T_EDGE_PORTGROUP_EXT: {{nsx_t_edge_portgroup_ext}}
  NSX_T_EDGE_PORTGROUP_TRANSPORT: {{nsx_t_edge_portgroup_transport}}
  NSX_T_TEP_POOL_NAME: {{nsx_t_tep_pool_name}}
  NSX_T_TEP_POOL_CIDR: {{nsx_t_tep_pool_cidr}}
  NSX_T_TEP_POOL_GATEWAY: {{nsx_t_tep_pool_gateway}}
  NSX_T_TEP_POOL_START: {{nsx_t_tep_pool_start}}
  NSX_T_TEP_POOL_END: {{nsx_t_tep_pool_end}}
  NSX_T_TRANSPORT_ZONE: {{nsx_t_transport_zone}}
  NSX_T_HOSTSWITCH: {{nsx_t_hostswitch}}
  NSX_T_TRANSPORT_VLAN: {{nsx_t_transport_vlan}}
  NSX_T_T0ROUTER: {{nsx_t_t0router}}
  TEST_PAYLOAD: {{test_payload}}

groups:
- name: install
  jobs:
  - install-nsx-t

- name: cleanup
  jobs:
  - uninstall-nsx-t

resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest


resources:
- name: nsx-t-gen-pipeline
  type: git
  source:
    uri: https://github.com/sparameswaran/nsx-t-gen.git
    branch: master

# Download NSX-T 2.1 bits from
# https://my.vmware.com/group/vmware/details?downloadGroup=NSX-T-210&productId=673

- name: nsx-mgr-ova
  type: file-url
  source:
    #username: username
    #password: password
    url: http://10.85.24.5:9080/nsx-unified-appliance-2.1.0.0.0.7380167.ova   #nsx-unified-appliance-2.1.0.0.0.7395503.ova  
    filename: nsx-unified-appliance-2.1.0.0.0.7395503.ova  

- name: nsx-ctrl-ova
  type: file-url
  source:
    #username: username
    #password: password
    url: http://10.85.24.5:9080/nsx-controller-2.1.0.0.0.7380161.ova #nsx-controller-2.1.0.0.0.7395493.ova  
    filename: nsx-controller-2.1.0.0.0.7395493.ova  

- name: nsx-edge-ova
  type: file-url
  source:
    #username: username
    #password: password
    url: http://10.85.24.5:9080/nsx-edge-2.1.0.0.0.7380184.ova #nsx-edge-2.1.0.0.0.7395502.ova  
    filename: nsx-edge-2.1.0.0.0.7395502.ova  

# Download from https://my.vmware.com/group/vmware/details?productId=614&downloadGroup=OVFTOOL420#
- name: ovftool
  type: file-url
  source:
    #username: username
    #password: password
    url: http://10.85.24.5:9080/VMware-ovftool-4.2.0-5965791-lin.x86_64.bundle  
    filename: VMware-ovftool-4.2.0-5965791-lin.x86_64.bundle  
  

jobs:

- name: install-nsx-t
  plan:
  - aggregate:
    - get: nsx-t-gen-pipeline
    - get: nsx-mgr-ova
    - get: nsx-ctrl-ova
    - get: nsx-edge-ova
    - get: ovftool

  - task: install-nsx-t
    file: nsx-t-gen-pipeline/tasks/install-nsx-t/task.yml
    params: *nsx-t-gen-params


- name: uninstall-nsx-t
  plan:
  - aggregate:
    - get: nsx-t-gen-pipeline

  - task: uninstall-nsx-t
    file: nsx-t-gen-pipeline/tasks/uninstall-nsx-t/task.yml

